server:
  port: 8000
  servlet:
    context-path: /amz


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
#  datasource:
#    url: jdbc:sqlite:${user.home}/.db/amz.db
#    driver-class-name:


# storage file config
store:
  location: /tmp/upload_dir
#logging:
#  level: debug

