server:
  port: 8000
  servlet:
    context-path: /amz


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


# storage file config
store:
  location: /tmp/upload_dir