server:
  port: 8000
  servlet:
    context-path: /amz


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/houseof4_db52ayaf4m8s5w
    username: houseof4_ur5xnqpsvdfhr
    password: sYGAkL8gaAPhx3V
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true


#  datasource:
#    url: jdbc:sqlite:${user.home}/.db/amz.db
#    driver-class-name:


# storage file config
store:
  location: /tmp/upload_dir

logging:
  level:
    ROOT: info
#    org.springframework.data.mongodb: info
#    org.mongodb.driver.protocol.command: info

---
spring:
  profiles:
    active: default

---
spring:
  profiles: ludev
#  data:
#    mongodb:
#      uri: mongodb://amz:amz@172.23.45.194:27017/amz

---
spring:
  profiles: ludep
#  data:
#    mongodb:
#      uri: mongodb://amz:amz@172.23.45.194:27017/amz
server:
  servlet:
    context-path: /cashier
