server:
  port: 8000
  servlet:
    context-path: /amz


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      port: 27017
  mongodb:
    embedded:
      version: 3.2.2
      storage:
        database-dir: ${user.home}/.db/mongo/

#  datasource:
#    url: jdbc:sqlite:${user.home}/.db/amz.db
#    driver-class-name:


# storage file config
store:
  location: /tmp/upload_dir

#logging:
#  level:
#    ROOT: DEBUG
